import numpy as np


def gmm_e_step(
    input: np.ndarray, weights: np.ndarray, means: np.ndarray, variances: np.ndarray
) -> np.ndarray:
    """
    input:     shape (n_samples, n_features)
    weights:   shape (k,), mixing proportions, sum to 1
    means:     shape (k, n_features)
    variances: shape (k, n_features), diagonal covariance (per-feature
    variance, no cross-feature covariance terms)

    Returns:
        shape (n_samples, k): "responsibilities", each row sums to 1.
        responsibilities[i, j] is the posterior probability that
        sample i was generated by component j.
    """
    # TODO: For each sample i and component j, compute
    # log(weights[j]) + gaussian_log_likelihood(input[i], means[j], variances[j]).
    # Then normalize each row of log-responsibilities into a proper
    # probability distribution: subtract the row max first (for
    # numerical stability), exponentiate, divide each row by its sum.
    pass


def gmm_m_step(
    input: np.ndarray, responsibilities: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Returns updated (weights, means, variances), same shapes as gmm_e_step's inputs.
    """
    # TODO: effective_counts[j] = sum over samples of responsibilities[:, j].
    # weights[j] = effective_counts[j] / n_samples.
    # means[j] = weighted average of input, weighted by responsibilities[:, j].
    # variances[j] = weighted average of (input - means[j])**2, weighted
    # the same way, per feature.
    pass
