import numpy as np


def dropout_forward(x: np.ndarray, mask: np.ndarray, p: float) -> np.ndarray:
    """
    Applies "inverted dropout": zeroes out the entries where `mask == 0`
    and rescales the surviving entries by 1 / (1 - p), so the output's
    expected value matches the input's, with no scaling needed at
    inference time. `mask` is a 0/1 array the same shape as `x`
    (1 = keep, 0 = drop), already generated by the caller.
    """
    pass


def dropout_backward(grad_output: np.ndarray, mask: np.ndarray, p: float) -> np.ndarray:
    """
    The backward pass of dropout_forward, given the SAME mask and p used
    on the forward pass.
    """
    pass
